=== virfaure/magento2-examples/LocalizedWelcome/etc/welcome.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:redefine schemaLocation="urn:magento:framework:Data/etc/argument/types.xsd">
  </xs:redefine>
  <xs:element name="welcome_message" type="welcome_messageType"/>
  <xs:complexType name="stateType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="code" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="countryType">
    <xs:sequence>
      <xs:element type="stateType" name="state" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="code" use="required"/>
  </xs:complexType>
  <xs:complexType name="welcome_messageType">
    <xs:sequence>
      <xs:element type="countryType" name="country" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== virfaure/magento2-examples/LocalizedWelcome/etc/welcome.xml
<?xml version="1.0"?>
<welcome_message
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:training1:LocalizedWelcome/etc/welcome.xsd">
    <country code="us">
        <state code="default">Welcome dear visitor!</state>
        <state code="TX">Howdy</state>
        <state code="CA">Hi</state>
        <state code="NY">Hello NY!</state>
    </country>
    <country code="ua">
        <state code="default">ласкаво просимо!</state>
    </country>
    <country code="de">
        <state code="default">Herzlich Willkommen!</state>
    </country>
    <country code="fr">
        <state code="default">Bonjour!</state>
    </country>
</welcome_message>
